#
###################################
# Site wide configuration
####################################
#
title: Cass Wilkinson Saldaña
email: cass.z.ws@gmail.com
description: Data librarian & data scientist 
url: https://www.cassws.net # the base hostname & protocol for your site
keywords: ["Programming", "Python", "Data Science", "Data Librarian", "Critical Data Literacies", "Pinball", "Cats"]

#
###################################
# Jekyll configuration
####################################
#
timezone:          US/Eastern
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: Zoë Wilkinson Saldaña
  avatar: zoews_square_small.jpg
  job: "Data scienctist + data librarian"
  # bio: "Data, cats, pinball, Python, NLP"
  email: zoewsaldana@gmail.com
#   disqus-shortname: renyuanzblog
  twitter: zoedottxt #username
  facebook: #username
  google:
    plus: #username
#     analytics: UA-62251910-2
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: zoews #username
#   stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
#   linkedin: renyuan-zou-69b7038a #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username
  telegram: #username
